name: Deploy Helm Chart to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Authenticate to Artifact Registry
        run: |
          echo "${{ secrets.GCP_KEY }}" | gcloud auth activate-service-account --key-file=-
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Login to Artifact Registry
        run: |
          echo "${{ secrets.GCP_KEY }}" | helm registry login us-central1-docker.pkg.dev \
            --username _json_key \
            --password-stdin

      - name: Pull Helm Chart from Artifact Registry
        run: |
          helm chart pull oci://us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/instance-registry/ping:0.1.0

      - name: Install Helm Chart
        run: |
          helm upgrade --install ping oci://us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/instance-registry/ping:0.1.0 \
            --namespace default
