name: Deploy Helm Chart to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        run: |
          echo "${{ secrets.GCP_KEY }}" | base64 -d > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Install GKE Auth Plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates gnupg curl
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Get GKE Cluster Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} \
            --region ${{ secrets.CLUSTER_LOCATION }} \
            --project ${{ secrets.PROJECT_ID }}
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: "true"

      - name: Verify kubectl Context
        run: kubectl config current-context

      - name: Configure Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          helm registry login us-central1-docker.pkg.dev \
            --username _json_key \
            --password "$(cat /tmp/key.json)"

      - name: Deploy Helm Chart from Local Package
        run: |
          helm upgrade --install ping ./output/ping-0.1.0.tgz \
            --namespace default

      - name: Deploy Helm Chart from Artifact Registry
        run: |
          helm upgrade --install ping oci://us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/instance-registry/ping \
            --namespace default \
            --version 0.1.0