name: Deploy Helm Chart to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Helm Chart
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Autenticación con Google Cloud
      - name: Authenticate to GCP
        run: |
          echo "${{ secrets.GCP_KEY }}" > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}

      # 3. Configurar acceso al Artifact Registry
      - name: Configure Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          helm registry login us-central1-docker.pkg.dev \
            --username _json_key \
            --password "$(cat /tmp/key.json)"

      # 4. Descargar e instalar el chart desde Artifact Registry
      - name: Deploy Helm Chart
        run: |
          helm upgrade --install ping oci://us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/instance-registry/ping \
            --namespace default \
            --version 0.1.0
