name: Deploy Helm Chart to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Helm Chart
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Authenticate to GCP
      - name: Authenticate to GCP
        run: |
          echo "${{ secrets.GCP_KEY }}" | base64 -d > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}

      # 3. Verify GCP Authentication (optional)
      - name: Verify GCP Authentication
        run: gcloud auth list

      # 4. Configure access to Artifact Registry
      - name: Configure Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          helm registry login us-central1-docker.pkg.dev \
            --username _json_key \
            --password "$(cat /tmp/key.json)"

      # 5. Deploy Helm Chart
      - name: Deploy Helm Chart
        run: |
          helm upgrade --install ping oci://us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/instance-registry/ping \
            --namespace default \
            --version 0.1.0

      # 6. Clean up (optional)
      - name: Clean up
        if: always()
        run: rm -f /tmp/key.json
