name: Deploy Helm Chart to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate to GCP
        run: |
          echo "${{ secrets.GCP_KEY }}" > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Authenticate Helm to Artifact Registry
        run: |
          helm registry login us-central1-docker.pkg.dev \
            --username _json_key \
            --password "$(cat /tmp/key.json)"

      - name: Pull Helm Chart from Artifact Registry
        run: |
          helm chart pull oci://us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/instance-registry/ping:0.1.0

      - name: Install Helm Chart
        run: |
          helm upgrade --install ping oci://us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/instance-registry/ping:0.1.0 \
            --namespace default
