name: Deploy Helm Chart to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Get GKE Cluster Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} \
          --region ${{ secrets.CLUSTER_LOCATION }} \
          --project ${{ secrets.PROJECT_ID }}
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: "true"

      - name: Configure Helm for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          helm registry login us-central1-docker.pkg.dev \
            --username _json_key \
            --password "${{ secrets.GCP_KEY }}"

      - name: Pull Helm Chart from Artifact Registry
        run: |
          helm chart pull oci://us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/instance-registry/ping:0.1.0
          helm chart export oci://us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/instance-registry/ping:0.1.0 \
            --destination ./charts

      - name: Install Helm Chart
        run: |
          helm upgrade --install ping ./charts/ping \
            --namespace default \
            --version 0.1.0
