name: Deploy Helm Chart to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Get GKE Cluster Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} \
          --region ${{ secrets.CLUSTER_LOCATION }} \
          --project ${{ secrets.PROJECT_ID }}
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: "true"

      - name: Configure Helm for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          helm repo add instance-registry oci://us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/instance-registry
          helm repo update

      - name: Install Helm Chart
        run: |
          helm upgrade --install ping instance-registry/ping \
            --namespace default \
            --version 1.0.0
